config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 resources :books
 root 'books#index'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :find_book, only: [:show, :edit, :update, :destroy]

def index
	@books = Book.all.order("created_at DESC")
end
def show
	@book = Book.find(params[:id])
	end

def new
	@book =  current_user.books.build
	@categories = Category.all.map{ |c| [c.name, c.id]}
	end
	


	def create
		@book = current_user.books.build(book_params)
		if @book.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @book.update(book_params)
			redirect_to book_path(@book)
		else
			render 'edit'
	end
end

	def destroy
		@book.destroy 
		redirect_to root_path
	end

	private

	def book_params
		params.require(:book).permit(:title, :description, :author, :category_id) 
	end

	def find_book
		@book = Book.find(params[:id])

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
	<%= simple_form_for @book do |f| %>
	<%= f.select(:category_id, options_for_select(@categories),:prompt => "Select a category")%>
  <%= f.input :title, label: "book Title" %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>  

app/views/books/index.html.erb
<% @books.each do |book| %>
<h2><%= link_to book.title, book_path(book) %></h2>
<% end %>

app/views/books/new.html.erb
<h1>new book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<h3><%= @book.author %></h3>
<p><%= @book.description %></p>
<%= link_to "back", book_path(@book)%>
<%= link_to "edit", edit_book_path(@book)%>
<%= link_to "Delete" ,book_path(@book), method: :delete, data:{ confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">

    <div class="container">
      <div class="navbar-header">
        <%= link_to "BookReview", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li><%= link_to "Add-Book",new_book_path %></li>
      <% end %>
      </ul>
    </div>

  
  </nav>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>